In [1]:
import numpy as np

In [9]:
a = np.random.rand(9)
a = np.reshape(a , (3, 3))
a

array([[0.81651205, 0.79485403, 0.57637677],
       [0.93359631, 0.23725057, 0.92816057],
       [0.97775079, 0.18886893, 0.12613885]])

In [11]:
col = np.sum(a, axis=0)
col

array([2.72785915, 1.22097354, 1.63067618])

In [13]:
percentage = 100 * a/col
percentage

array([[29.93233908, 65.10002138, 35.34587511],
       [34.22450567, 19.4312624 , 56.91875413],
       [35.84315525, 15.46871622,  7.73537076]])